name: CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - '*'

jobs:
  build:
    name: MacOS
    runs-on: macos-12
    steps:
    - uses: actions/checkout@v3
    - name: Select Xcode 14.2
      run: sudo xcode-select -s /Applications/Xcode_14.2.app
    - name: Run tests
      run: make test-swift

  ubuntu:
    name: Ubuntu
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3
    - name: Run tests
      run: make test-linux
